"""Remove links from collection

Revision ID: 7f507d5f6dea
Revises: 68d39ac155ac
Create Date: 2020-12-13 08:03:27.889652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f507d5f6dea'
down_revision = '68d39ac155ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'links')
    op.add_column('link', sa.Column('collection', sa.String(), nullable=True))
    op.create_foreign_key(None, 'link', 'collection', ['collection'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.drop_column('link', 'collection')
    op.add_column('collection', sa.Column('links', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
