"""empty message

Revision ID: a61c96707c39
Revises: b9870883aa56
Create Date: 2020-12-21 07:44:31.450653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61c96707c39'
down_revision = 'b9870883aa56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('collection_name_key', 'collection', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('collection_name_key', 'collection', ['name'])
    # ### end Alembic commands ###
