"""temporarily remove owner from collection

Revision ID: efb436cb06f1
Revises: 7f507d5f6dea
Create Date: 2020-12-13 11:33:56.708191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb436cb06f1'
down_revision = '7f507d5f6dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('collection_owner_fkey', 'collection', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('collection_owner_fkey', 'collection', 'user', ['owner'], ['id'])
    # ### end Alembic commands ###
